version: '3.7'

x-base: &base
  env_file:
    - ./.env.dev
services:
  python:
    <<: *base
    build: ./services/python
    command: python app/main.py
    volumes:
      - ./services/python/:/usr/src/app/
